### ISSUE TITLE
Does not have EFI/ Boot folder in it.

### ISSUE THREAD

**Issue by fabihahashmat-sheikh** [Mattiwatti/EfiGuard#10]
I have downloaded from below link while following the steps stated for "Booting the loader" but could not find EFI/ Boot folder in it and so cannot proceed with the next steps to use.
https://github.com/Mattiwatti/EfiGuard

**Comment by Mattiwatti** [comment]
What do you mean by "in it"? In the ZIP file? Because it does contain an `EFI/Boot` folder. Or do you mean on a USB stick or virtual disk? If so, you just need to create the folders and put the EfiGuard files there as per the README.
