### ISSUE TITLE
Disabling DSE...

### ISSUE THREAD

**Issue by DudeBelowMeSucks** [Mattiwatti/EfiGuard#100]
Microsoft Windows [Version 10.0.19045.3324]
(c) Microsoft Corporation. All rights reserved.

C:\WINDOWS\system32>cd C:\Users\GGB BIGMIKE\Desktop\EfiGuard-v1.3

C:\Users\GGB BIGMIKE\Desktop\EfiGuard-v1.3>EfiDSEFix.exe -d
Disabling DSE...
CI!g_CiOptions at 0xFFFFF80452239418.
Failure: NtSetSystemEnvironmentValueEx error 0xC000000D
The EfiGuard DXE driver is either not loaded in SETVARIABLE_HOOK mode, or it is malfunctioning.
AdjustCiOptions failed: 0xC000000D

C:\Users\GGB BIGMIKE\Desktop\EfiGuard-v1.3>

**Comment by Mattiwatti** [comment]
What is the issue here? The error message tells you the reason for the error. Is it incorrect? Or else, what is your question?
