### ISSUE TITLE
Patch fail

### ISSUE THREAD

**Issue by Tomatcree01** [Mattiwatti/EfiGuard#103]
![failnew](https://github.com/Mattiwatti/EfiGuard/assets/76787776/83594c1c-03a9-454f-83a8-a68f15cf84fc)
![Screenshot 2023-09-03 014754](https://github.com/Mattiwatti/EfiGuard/assets/76787776/7d1ab1b9-6677-4fa2-88f4-312f0741fbc3)

**Comment by Mattiwatti** [comment]
Thanks. I fixed this in 5195ae9 but I forgot to reference the issue.
