### ISSUE TITLE
I need some help on a project I'm currently working on 

### ISSUE THREAD

**Issue by sudo-000** [Mattiwatti/EfiGuard#104]
Hi, 
I'm now working on a project that is trying to achieve the same thing but in another way: 
The aim of this project is to break those frustrating restrictions in Windows, such as DSE. 
I achieved this by modifying files on the harddisk via IDA so I don't have to waste time patching the kernel over and over again on each startup. 
Besides that, another great achievement that could be made is the support for legacy boot! 
What's best about it is that the modified OS can be packed into an ISO and perform a batch installation on multiple devices. 
The only drawback of this is probably getting banned by anti-cheats. But that doesn't bother me very much since I mostly play offline games. 

However, I need some tutorials from you on what to change in which function in which file. 

The targeted OS that I'm making patches on is Windows 11 21H1 Build 22000.318. 
The OS is booted with legacy boot, and I'm not planning to provide UEFI support anytime soon. 
YES, you didn't read anything wrong, I BOOTED WINDOWS 11 WITH LEGACY!!! 
If you wanna know how I achieve this, reply to me and I'll tell you. 
In my case, if I'm guessing correctly I should not be modifying any *.efi file, right? 

The tutorial that I'm currently following tells me to modify 3 files: 
ntoskrnl.exe
winload.exe
bootmgr.exe

But I've noticed in the source code of your program that you modified more than three files in the memory during boot. 
Also I noticed that you've changed some other functions in ntoskrnl.exe that the current tutorial didn't mention. 

Could you please give me an explanation on the things that have been changed and whether the modification is still necessary on legacy boot. Thanks! 

If possible, I also wanna kill the PE checksum verification of ntoskrnl.exe and winload.exe. So I don't have to correct the checksum everytime I make some changes to the system. 
Otherwise, whenever I forget to correct the checksum after modifying a system file, my computer will just get stuck in a bootstrap and doesn't let me do anything, which I don't want.

**Comment by Mattiwatti** [comment]
Either send me an email about your project (as well as followups telling me to reply ASAP...) **or** make an issue, not both. Thanks.
