### ISSUE TITLE
Startup

### ISSUE THREAD

**Issue by IvankoEanko** [Mattiwatti/EfiGuard#29]
Is it possible to do something so that I do not have to turn this entire operation in the boot every time?

**Comment by Mattiwatti** [comment]
Yes, you can install EfiGuard on the Windows ESP partition and make a boot entry for it. See [this comment on issue #2](https://github.com/Mattiwatti/EfiGuard/issues/2#issuecomment-478998015) for instructions.

**Comment by IvankoEanko** [comment]
I have only network devices in UEFI.

**Comment by IvankoEanko** [comment]
What is X?
![image](https://user-images.githubusercontent.com/42719199/119355112-8b750c00-bcad-11eb-8be4-3c3224fc6444.png)

**Comment by IvankoEanko** [comment]
I am stuck on this, I try to do it 100 times but it doesn't work. I don't understand what X is, I thought it was a flash drive. In my case, this is E, but if I type E it says that the Folder is not empty. Also, the cd command does not work in effi for some reason. Is there a video about it anywhere?

**Comment by IvankoEanko** [comment]
I have done it. Ty
