### ISSUE TITLE
Startup problem 2

### ISSUE THREAD

**Issue by IvankoEanko** [Mattiwatti/EfiGuard#30]
I did everything according to the guide, a message was displayed for me, I even checked the dump to see if my EfiGuard remained there in 1st place. But when you reboot, it disappears from startup

**Comment by Mattiwatti** [comment]
I'm assuming (based on the previous issue you created) that you're referring to installing EfiGuard on the Windows ESP...

If `bcfg boot dump` in the UEFI shell shows EfiGuard, then it exists in the BIOS boot entries. Check your BIOS startup options. Some firmwares get confused when there are multiple boot entries for the same drive, and/or will add the new entry but place it at the back. Look for 'boot entry order', 'BBS disk order', 'disk boot order' or similar. Chances are you will find at least two entries:
- Windows Boot Manager
- EfiGuard

If so, swap their order so that EfiGuard is first, but do not remove the Windows Boot Manager entry because EfiGuard needs it to find Windows.

**Comment by Mattiwatti** [comment]
I'm guessing that by 'EfiGuard dump', you mean the output of `bcfg boot dump` in the UEFI shell...

> I put it in 0 place, after Windows

Either you put it in 0th place (i.e. it's the first entry), or you put it after Windows, not both. EfiGuard should be listed *before* Windows in the output of `bcfg boot dump`.

Again, check your BIOS options. What `bcfg` tells you does not always correspond to what the BIOS will actually do, especially if there are multiple boot entries on the same drive.

**Comment by IvankoEanko** [comment]
![20210525_223342](https://user-images.githubusercontent.com/42719199/119558141-b9d81180-bda9-11eb-94b0-a00a2b4e3aa6.jpg)
![20210525_223252](https://user-images.githubusercontent.com/42719199/119558147-bba1d500-bda9-11eb-9b81-2b96552ba8fa.jpg)

**Comment by IvankoEanko** [comment]
But it disappears after reloading one more time

**Comment by IvankoEanko** [comment]
> I'm guessing that by 'EfiGuard dump', you mean the output of `bcfg boot dump` in the UEFI shell...
> 
> > I put it in 0 place, after Windows
> 
> Either you put it in 0th place (i.e. it's the first entry), or you put it after Windows, not both. EfiGuard should be listed _before_ Windows in the output of `bcfg boot dump`.
> 
> Again, check your BIOS options. What `bcfg` tells you does not always correspond to what the BIOS will actually do, especially if there are multiple boot entries on the same drive.

i dont know. I'm downloading this from a USB stick and I noticed that EfiGuard has optional N and all others have Y. Maybe this is the case?

**Comment by Mattiwatti** [comment]
> i dont know. I'm downloading this from a USB stick and I noticed that EfiGuard has optional N and all others have Y. Maybe this is the case?

No, this is unrelated and a side effect of the entry being added by `bcfg`.

Your screenshot is showing a path to EfiGuard that is on a USB drive, not on the Windows EFI partition you are (as I understand it) trying to use... you either have EfiGuard installed in the wrong place, or you are invoking `bcfg` from the wrong drive or with the wrong path.

Furthermore, your USB drive is formatted as MBR and not as GPT. (This is OK for USB drives on some motherboards, but there are also plenty of motherboards that will not accept this.)

Both of the above _could_ be reasons why your BIOS is deciding to throw out the boot entry. I really don't know.

**Comment by IvankoEanko** [comment]
> > i dont know. I'm downloading this from a USB stick and I noticed that EfiGuard has optional N and all others have Y. Maybe this is the case?
> 
> No, this is unrelated and a side effect of the entry being added by `bcfg`.
> 
> Your screenshot is showing a path to EfiGuard that is on a USB drive, not on the Windows EFI partition you are (as I understand it) trying to use... you either have EfiGuard installed in the wrong place, or you are invoking `bcfg` from the wrong drive or with the wrong path.
> 
> Furthermore, your USB drive is formatted as MBR and not as GPT. (This is OK for USB drives on some motherboards, but there are also plenty of motherboards that will not accept this.)
> 
> Both of the above _could_ be reasons why your BIOS is deciding to throw out the boot entry. I really don't know.



That is, I need to shove your files to the Windows boot?

**Comment by Mattiwatti** [comment]
If you want to add EfiGuard as a permanent boot entry, then yes, I would recommend doing so. It may be possible to add permanent USB boot entries by filename on some motherboards, but in general I would say it is not reliable.

In the [previous issue you made](https://github.com/Mattiwatti/EfiGuard/issues/29), you quoted the exact steps needed to do this. I don't know where the confusion is coming from.

**Comment by IvankoEanko** [comment]
> If you want to add EfiGuard as a permanent boot entry, then yes, I would recommend doing so. It may be possible to add permanent USB boot entries by filename on some motherboards, but in general I would say it is not reliable.
> 
> In the [previous issue you made](https://github.com/Mattiwatti/EfiGuard/issues/29), you quoted the exact steps needed to do this. I don't know where the confusion is coming from.

I do not have access to Windows boot, in the last topic I thought that everything was fine, because at startup I got an inscription, after another restart, the inscription disappeared.

**Comment by IvankoEanko** [comment]
> If you want to add EfiGuard as a permanent boot entry, then yes, I would recommend doing so. It may be possible to add permanent USB boot entries by filename on some motherboards, but in general I would say it is not reliable.
> 
> In the [previous issue you made](https://github.com/Mattiwatti/EfiGuard/issues/29), you quoted the exact steps needed to do this. I don't know where the confusion is coming from.

When I start it manually, everything works, but if I want to make it as autoload, then Windows is loaded
![0-02-05-dee2093297fee4c635aad6698b3593251601313966b7109f3e880cb937b4dfac_87c06bbcb9f3df27](https://user-images.githubusercontent.com/42719199/120026336-96f06c00-bffa-11eb-8843-55562dbfe60c.jpg)
![0-02-05-9045e3bad006414f7293b09bfd3ae56bd4492f781228c501d8d6eeeb9e201059_c76ec3b8e8528891](https://user-images.githubusercontent.com/42719199/120026509-db7c0780-bffa-11eb-80a5-59f800e2f698.jpg)
I installed it and it boots fine, but after rebooting the system.
![0-02-05-7a69fb9a335e83cade5180802dd0c938a3ed95de23e372b75eda2424d7c0a854_e76a2421941cff85](https://user-images.githubusercontent.com/42719199/120026416-b7202b00-bffa-11eb-961c-16040882bef7.jpg)

**Comment by IvankoEanko** [comment]
My usb is 
![0-02-05-1c62d60cdcc3c5b24daf6dffe806c6241ad71d6efbcdf43e1a8faffd1bfae1ac_f69b7ec966cab45a](https://user-images.githubusercontent.com/42719199/120026799-488f9d00-bffb-11eb-8e66-ec9cc0f65f84.jpg)

**Comment by IvankoEanko** [comment]
Solved. Enable Legacy mode and disable boot mod.
