### ISSUE TITLE
Inquiry

### ISSUE THREAD

**Issue by tatareq** [Mattiwatti/EfiGuard#33]
Hello
Can you help me Please  get it working on All new Windows 10 versions 
I am Using Before this tools UPGDSED-dev version 1.3.0 but this version just support Windows 10 version 1803
Please Can you Help me 

Best Regards
Thanks

**Comment by BlackBunnyHunter** [comment]
Works for me on version 20h2 (OS Build 19042.985)

**Comment by tatareq** [comment]
how please can you give me explain 
how i can make
please

**Comment by BlackBunnyHunter** [comment]
Just follow the instructions in the read me

**Comment by Mattiwatti** [comment]
I believe everything that needed saying has been said here. If you cannot follow the instructions in the `README`, this program is probably not for you.
