### ISSUE TITLE
Failure: NtSetSystemEnvironmentValueEx error C000000D

### ISSUE THREAD

**Issue by zjkanjie** [Mattiwatti/EfiGuard#44]
Error executing efidsefix.exe -d

Disabling DSE...
CI!g_CiOptions at 0xFFFFF8034E4283B8.
Failure: NtSetSystemEnvironmentValueEx error C000000D
AdjustCiOptions failed: C000000D

EfiDSEFix.exe -i
SystemBootEnvironmentInformation:
        - BootIdentifier: {f45c4fdd-b208-11eb-bfac-f6a794726b32}
        - FirmwareType: UEFI
        - BootFlags: 0x0

SystemModuleInformation:
        - Kernel: ntoskrnl.exe (\SystemRoot\system32\ntoskrnl.exe)

SystemCodeIntegrityInformation:
        - IntegrityOptions: 0x0001

SystemKernelDebuggerInformation:
        - KernelDebuggerEnabled: 0
        - KernelDebuggerNotPresent: 1

SystemKernelDebuggerInformationEx:
        - DebuggerAllowed: 0
        - DebuggerEnabled: 0
        - DebuggerPresent: 0

SharedUserData->KdDebuggerEnabled: 0x00

SystemKernelDebuggerFlags: 0x00

SystemCodeIntegrityPolicyInformation:
        - Options: 0x40000000
        - HVCIOptions: 0x0000

**Comment by pineda89** [comment]
@zjkanjie how you solve it?
