### ISSUE TITLE
Cant install efiguard

### ISSUE THREAD

**Issue by quinnzaballa** [Mattiwatti/EfiGuard#62]
Bios mode = UEFI
HVCI = Disabled
Secure boot = disabled
(Hyper Virtualization, and virtualization is enabled; do i need to disable it?)
I dont know how does a320m-k mboard works but i cant figured out whats the problem.

I renamed the loader.efi to bootx64.efi and boots and like i saw in youtube. it doesnt show anything just boots normally. and putting the command with -i this is what it shows.

![image](https://user-images.githubusercontent.com/58278258/180720744-530d9623-a53f-4390-a49c-30c8c1fc6fb3.png)

im bad at english.
let me know if you want me to send more information.
also im using 64bit windows 10 enterprise: build 19044
is this version not supported?
I've heard enterprise is strict on securities

**Comment by Mattiwatti** [comment]
> (Hyper Virtualization, and virtualization is enabled; do i need to disable it?)

I assume you mean Hyper-V. If so, yes, see #57.

Other than that it sounds to me like you are simply using the wrong boot entry, because you would definitely see *something* happen if you booted the loader. You need to set up the boot order in your BIOS so that the loader will actually be booted.
