### ISSUE TITLE
Having a problem with Efiguard

### ISSUE THREAD

**Issue by Madfuckingman** [Mattiwatti/EfiGuard#63]
Hello. I'm trying to install Efiguard, but it doesn't boot at all (USB Stick). I've done all the steps but it just boots at windows, even putting to boot at my USB Stick on BIOS doens't work. I don't have neither Secure Boot or Hyper-V enabled. I'm using Windows 10 Education 21H2.

![cmd_guiG7gR1AS](https://user-images.githubusercontent.com/63427458/185767258-364f39f5-d805-426b-be72-303381d1d675.png)

Also
![cmd_Je72pnb148](https://user-images.githubusercontent.com/63427458/185821692-dd871015-4556-439a-b1d7-06ee458f4831.png)

**Comment by Mattiwatti** [comment]
As shown by the output of `EfiDSEFix -i`, your Windows installation is a legacy one ("FirmwareType: BIOS"). EfiGuard does not support non-UEFI installations of Windows.

**Comment by Madfuckingman** [comment]
I see, thanks for the help. I've used mbr2gpt command on my SSD and was able to change to UEFI mode.
