### ISSUE TITLE
LoadImage Error 800000000000E (not found)

### ISSUE THREAD

**Issue by AdmiralNicherov** [Mattiwatti/EfiGuard#65]

**Comment by adzkii-i** [comment]
shouldn't the BIO be UEFI for EFIGUARD to work? ur bio is legacy

**Comment by AdmiralNicherov** [comment]
> shouldn't the BIO be UEFI for EFIGUARD to work? ur bio is legacy


I have uefi enabled on the second photo you can see

**Comment by AdmiralNicherov** [comment]
> shouldn't the BIO be UEFI for EFIGUARD to work? ur bio is legacy

I have uefi enabled on the second photo you can see

**Comment by AdmiralNicherov** [comment]
mbr2gpt finish problem
