### ISSUE TITLE
EAC Patched Windows boot loader detected. (Kernel Patch Protection disabled)

### ISSUE THREAD

**Issue by Pain160710** [Mattiwatti/EfiGuard#76]
When try to start The Division 2 which is protected by EAC, i get this message after using EfiGuard.

1. I`ve booted from the USB-Stick with the EfiGuard files
2. I`ve opened the cmd as admin, navigated to the save directory of EfiGuard and entered this command: Efidsefix.exe -d
3. After that i started modded CheatEngine without a problem
4. After that i entered this command in the same cmd window: Efidsefix.exe -e
5. Finally i started the game and got the message: "Patched Windows boot loader detected. (Kernel Patch Protection disabled)"
Do you have any workaround for this problem?

Thank you and have a nice evening, best regards.
![EAC_error](https://user-images.githubusercontent.com/61328895/219896711-2a4b8443-3883-4b03-bc03-8dd05f1116f8.png)

**Comment by DecoderCoder** [comment]
Can you check other game?
And by the way, check this https://github.com/ByteWhite1x1/PatchGuardResearch

**Comment by Mattiwatti** [comment]
See #66.
