### ISSUE TITLE
Efi does not support legacy (non-UEFI)

### ISSUE THREAD

**Issue by kimi1233212** [Mattiwatti/EfiGuard#77]
![image](https://user-images.githubusercontent.com/110891929/222719383-ef404d32-38d0-42ed-8168-88db0e977d57.jpeg)

**Comment by kimi1233212** [comment]
Uh guys after I change all thing to the UEFI then my computer can't be boot

**Comment by Mattiwatti** [comment]
The message already told you what the problem is, I'm not sure how I could possibly make this clearer.
