### ISSUE TITLE
Unable to boot after installing Window 11

### ISSUE THREAD

**Issue by SK-y-Y** [Mattiwatti/EfiGuard#83]
![8078D207-5A93-4A47-A51B-EC3FB0D1C844](https://user-images.githubusercontent.com/118031041/230791577-06a92bd0-2011-4859-92b2-132766b11b4b.jpeg)
After installing EFI deleting loader config and renaming to bootx64 after resetting pc. and going into bios.
1) I'm unable to boot override into the flash drive i have with the efi
2) after rearranging my boot config it will go into window recovery mode
3) eufi shell cannot be found.
4)At first it worked and loaded the EFI but then didn't go into windows like it supposed to

please let me know if you need any screenshots or any other information so i can get it working. 

Thank you for your time!
![E9098FA9-2A95-4231-9F70-6673FB32328D](https://user-images.githubusercontent.com/118031041/230791582-163512b8-3c30-4eb8-aa7d-9f2b9000bc9a.jpeg)

(Edit) I was able to boot via override after doing a fresh install of the efi zip but wasn’t able to ge tit to work in admin panel after

**Comment by Mattiwatti** [comment]
I'm a bit confused as to what your actual issue(s) is/are now. I see - I think - three different issues listed, plus the photos which to me seem to be yet another one. Then your edit on top of this doesn't really help to clarify to me what now remains as the issue (or is this something else again?). I have to say that none of the things you mention look like issues with EfiGuard to me, though if you clarify further I can try to help with installation/usage.

Re: your photos: this one is pretty easy at least: you are trying to launch EfiDSEFix.exe from PowerShell but not prepending the required `.\` prefix for files in the current directory. This doesn't work for any program, including EfiDSEFix. Either run the same command from a `cmd.exe` shell or run `.\EfiDSEFix.exe` instead.
