### ISSUE TITLE
Question 

### ISSUE THREAD

**Issue by NightRaidGamer** [Mattiwatti/EfiGuard#86]
hello I would like to know if this bootkit supports old systems that are not compatible with UEFI?

**Comment by Mattiwatti** [comment]
Nope. Sorry.

**Comment by NightRaidGamer** [comment]
> Nope. Sorry.

could you add support in the future?

**Comment by Mattiwatti** [comment]
No, not really. EfiGuard relies on a number of things present in UEFI (like EFI runtime services) which do not exist in BIOS - this the reason why it's named EfiGuard.

**Comment by NightRaidGamer** [comment]
> No, not really. EfiGuard relies on a number of things present in UEFI (like EFI runtime services) which do not exist in BIOS - this the reason why it's named EfiGuard.

what about MBR and VBR ?

**Comment by Mattiwatti** [comment]
What about them? Those are just ways (well, places) to gain code execution, which is not the issue.
